### ISSUE TITLE
Weird symbols imported when using SLIME

### ISSUE THREAD

**Issue by nklein** [eugeneia/maxpc#2] opened 2016-09-06 18:25 UTC
I can't explain why this would be.  It may be some quirk of my system setup, but I can't see how.

I am using CCL 1.10-r16196 on Linux.  I will try it on a newer CCL later today.  I am using SLIME from Quicklisp.

When I do things from the command-line, nothing weird happens:

``` common-lisp
? (load "maxpc/maxpc.asd")
#P"/home/pat/tmp/maxpc/maxpc.asd"
? (asdf:load-system :maxpc :force t)
;Compiler warnings for "home:tmp;maxpc;input.lisp.newest" :
;   In (INPUT-SEQUENCE (T INTEGER)) inside an anonymous lambda form: Unused lexical variable INPUT
; Warning: Lisp compilation had style-warnings while compiling #<CL-SOURCE-FILE "maxpc" "input">
; While executing: UIOP/LISP-BUILD:CHECK-LISP-COMPILE-WARNINGS, in process listener(1).
T
? (find-symbol "=ELEMENT")
NIL
NIL
```

However, when I do the same from within SLIME (in a brand-new REPL), the last call finds a symbol:

``` common-lisp
CL-USER> (load "maxpc/maxpc.asd")
#P"/home/pat/tmp/maxpc/maxpc.asd"
CL-USER> (find-symbol "=ELEMENT")
NIL
NIL
CL-USER> (asdf:load-system :maxpc :force t)
;Compiler warnings for "home:tmp;maxpc;input.lisp.newest" :
;   In (INPUT-SEQUENCE (T INTEGER)) inside an anonymous lambda form: Unused lexical variable INPUT
; Warning: Lisp compilation had style-warnings while compiling #<CL-SOURCE-FILE "maxpc" "input">
; While executing: UIOP/LISP-BUILD:CHECK-LISP-COMPILE-WARNINGS, in process repl-thread(12).
T
CL-USER> (find-symbol "=ELEMENT")
=ELEMENT
:INTERNAL
```

**Comment by nklein** [comment] 2016-09-06 18:29
If I load the files one-by-one into my SLIME REPL in the order they are in the ASD file, I do not end up with that symbol interned.  So... no idea....

**Comment by eugeneia** [comment] 2016-09-07 11:35
I can reproduce this on CCL 1.11.

**Comment by eugeneia** [comment] 2017-04-03 22:53
So I can’t reproduce this in CMUCL, so I’ll just ping @xrme even though I know he doesn’t use SLIME. Any idea what might cause it? Seems to be a CCL specific SLIME bug?

**Comment by xrme** [comment] 2017-04-03 23:49
Perhaps you could put some advice on `cl:intern` such that it would tell you when `=element` is getting interned into the cl-user package?  You could do something like

```
(advise intern (when (equalp "=ELEMENT" (car arglist)) (break))
	     :when :before)
```

before loading the system, and see if that shows anything unexpected.

I'm pretty sure not everything funnels through `cl:intern`, however, so another thing you could try is to use the internal facility that runs a hook when a symbol is interned into a package.  For example:
```
(setf (ccl::pkg.intern-hook (find-package "CL-USER")) (lambda (s) (format t "just interned ~s" s)))
```

**Comment by eugeneia** [comment] 2017-04-04 09:33
Thanks for the pointer @xrme, installing a break hook lead me to where this is happening. The line causing this seems to be this macro lambda list: https://github.com/eugeneia/maxpc/blob/master/more.lisp#L63

`(defmacro ?test ((test &rest arguments) &optional (parser '(=element))…`

Swank calls `(CCL::%ARGLIST 'MAXPC:?TEST NIL)` which interns the culprit symbol into the CL-USER package. Not sure if that is expected.

```
 19: (CCL::%ARGLIST MAXPC:?TEST NIL)
 20: (SWANK/BACKEND:ARGLIST MAXPC:?TEST)
 21: (SWANK::SYMBOL-INDENTATION MAXPC:?TEST)
```

**Comment by xrme** [comment] 2017-04-04 17:45
Sounds like http://trac.clozure.com/ccl/ticket/1260

**Comment by eugeneia** [comment] 2017-06-14 21:37
Fixed in https://github.com/Clozure/ccl/pull/47

**Closed as completed by eugeneia** 2017-06-14 21:37 UTC
Labels: help wanted
