### ISSUE TITLE
Unexpected behaviour when parsing from a stream

### ISSUE THREAD

**Issue by eudoxia0** [eugeneia/maxpc#9] opened 2017-11-18 15:25 UTC
When parsing directly from a character input stream, using a parser that doesn't accept any whitespace characters, I have to press <kbd>Return</kbd> twice to get the parser to finish.

E.g.:

```lisp
CL-USER> (maxpc:parse *standard-input* (maxpc.digit:=integer-number))
123⏎
⏎
123 (7 bits, #x7B, #o173, #b1111011)
T
NIL
```

I'm not sure what causes this, but some preliminary suspects might be handling of Windows vs. Unix newlines, or how the parser machinery keeps track of the input position.

**Comment by eugeneia** [comment] 2017-11-18 16:01
I think what you are experiencing is related to how your REPL forwards input to `*standard-input*`. The behavior you describe is not caused by MaxPC:

```
(with-input-from-string (in "123")
  (maxpc:parse in (maxpc.digit:=integer-number)))
→ 123, T, T
```

NB: I *think* what you are trying to do is parse user input using MaxPC like in the following example:

```
(loop do (maxpc:parse *standard-input* (maxpc.digit:=integer-number)))
```

This is *not* going to work: MaxPC buffers its input when reading from a stream (it needs to be able to go back to any position in the stream), so you can’t tell how many elements `parse` will read. You have to assume that `parse` consumes the input stream completely.

Does that help?

**Comment by eudoxia0** [comment] 2017-11-18 16:09
So, is there any way to write a REPL using a MaxPC parser as the read step? Or is it hopeless?

**Comment by eugeneia** [comment] 2017-11-18 16:18
There are many ways:

1. you could read the input from the stream before parsing it with MaxPC (i.e. using `READ-LINE` or `READ-MY-NEXT-REPL-COMMAND`)
2. you could implement  the REPL *in* MaxPC, i.e. `(maxpc:%any (?my-read-eval-print))` and only return from the parser when quitting the REPL
3. ....

What MaxPC can not do, is stop your existing CL REPL from needing two consecutive newlines to send a line to `*standard-input*` (in my experience this goes away when running the program from the command line).

**Comment by eudoxia0** [comment] 2017-11-18 16:34
The problem with 1. is `read-line` will read less than a full command in the case that REPL input can span more than one line, and a hypothetical `READ-MY-NEXT-REPL-COMMAND` function has the same problem that it's reading from `*standard-input*` using MaxPC.

>in my experience this goes away when running the program from the command line

I tried running this on CCL in the command line rather than Emacs but I still have the same problem. Or do you mean compiling the program to a binary and running the REPL from there?

**Comment by eugeneia** [comment] 2017-11-18 16:34
Oh, as a third option I guess you *can* do what I claimed you could not in https://github.com/eugeneia/maxpc/issues/9#issuecomment-345451565 by setting [\*chunk-size\*](http://mr.gy/software/maxpc/api.html#section-5-2) to 1.

**Comment by eugeneia** [comment] 2017-11-18 16:46
Note that MaxPC only reads from streams in `*chunk-size*` when its parsing from a `file-stream`, so the example in https://github.com/eugeneia/maxpc/issues/9#issuecomment-345451565 might even work with `*chunk-size*` > 1 as long as `*standard-input*` is an non-file stream.

Also note: you can always create your own types of input with any behavior you like, by implementing the [input](http://mr.gy/software/maxpc/api.html#section-4) interface. If you can divide your input into elements, MaxPC can most likely be used to parse it.

**Comment by eudoxia0** [comment] 2017-11-18 16:51
Hmm, no, changing the `*chunk-size*` doesn't work, I guess since `*standard-input*` is a normal character input stream.

**Comment by eugeneia** [comment] 2017-11-18 17:19
Actually, I was wrong: you did stumble upon a bug in the stream input implementation of MaxPC. The problem is that `input-rest` will ensure that the next element returned by `input-first` is available, which causes the stream implementation to wait for one more element than is actually needed to match the parser.

**Comment by eugeneia** [comment] 2017-11-19 23:08
@eudoxia0 I have pushed a fix to master. Thank you for reporting this issue! 👍 😄

**Closed as completed by eugeneia** 2017-11-19 23:08 UTC
Labels: bug

**Comment by eudoxia0** [comment] 2017-11-20 03:29
Thank you! The fix works perfectly 💯
